apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.name: grafana
    io.portainer.kubernetes.application.stack: grafana
  name: grafana-2
  namespace: monitoring
spec:
  ports:
  - name: port-0
    nodePort: 32300
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
  type: NodePort
