apiVersion: v1
kind: Service
metadata:
  labels:
    io.portainer.kubernetes.application.name: prometheus-k8s
    io.portainer.kubernetes.application.stack: prometheus-k8s
  name: prometheus-k8s-2
  namespace: monitoring
spec:
  ports:
  - name: port-0
    nodePort: 32090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: k8s
    operator.prometheus.io/shard: "0"
    prometheus: k8s
  sessionAffinity: None
  type: NodePort
